# Toronto Neighborhood - Segmentation and Clustering
Coursera  - IBM Data Science

## Part 1 - Data Exploration

In [1]:
#import required libraries
import pandas as pd
import numpy as np

In [2]:
#install web scraping tools for Pandas
!pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in /home/shripal/anaconda3/lib/python3.7/site-packages (4.5.0)
Requirement already satisfied: html5lib in /home/shripal/anaconda3/lib/python3.7/site-packages (1.0.1)
Requirement already satisfied: beautifulsoup4 in /home/shripal/anaconda3/lib/python3.7/site-packages (4.8.2)
Requirement already satisfied: webencodings in /home/shripal/anaconda3/lib/python3.7/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /home/shripal/anaconda3/lib/python3.7/site-packages (from html5lib) (1.14.0)
Requirement already satisfied: soupsieve>=1.2 in /home/shripal/anaconda3/lib/python3.7/site-packages (from beautifulsoup4) (1.9.5)

In [3]:
#toronto wikipedia website 
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [4]:
#rscrape website and load to Pandas dataframe
dfs = pd.read_html(url)

#get the table into data-frame
df = dfs[0]
df.head(5)

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [5]:
#rename colums Postal Code to PostalCode
df.rename(columns = {'Postal Code': 'PostalCode', 'Neighbourhood':'Neighborhood'}, inplace = True)
df.head()

  PostalCode           Borough               Neighborhood
0        M1A      Not assigned               Not assigned
1        M2A      Not assigned               Not assigned
2        M3A        North York                  Parkwoods
3        M4A        North York           Victoria Village
4        M5A  Downtown Toronto  Regent Park, Harbourfront

In [6]:
#drop rows of data where Borough and Neighbourhood not assigned to postal code
indexNames = df[ (df['Borough'] == 'Not assigned') & (df['Neighborhood'] == 'Not assigned')].index
df.drop(indexNames, inplace = True)

df2 = df.reset_index(drop=True)

df2.head()

  PostalCode           Borough                                 Neighborhood
0        M3A        North York                                    Parkwoods
1        M4A        North York                             Victoria Village
2        M5A  Downtown Toronto                    Regent Park, Harbourfront
3        M6A        North York             Lawrence Manor, Lawrence Heights
4        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [7]:
df2.shape

(103, 3)

## Part 2: Geocoding based on Toronto Postal Codes

In [169]:
#file with toronto postal codes
file = 'Geospatial_Coordinates.csv'

In [171]:
#Toronto postal codes csv file read into dataframe
df_coord = pd.read_csv(file)
df_coord.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [161]:
#function which returns lat. long values based on Toronto postal codes
def latlng(PostalCode):
    row = df_coord.loc[df_coord['Postal Code'] == PostalCode].index
    lat = df_coord.loc[row, 'Latitude'].tolist()
    lng = df_coord.loc[row, 'Longitude'].tolist()
    x = lat[0]
    y = lng[0]
    return x, y

In [198]:
#Add latitude and longitude columns in Toronto Data Frame
PostalCodes = [PostalCodes for PostalCodes in df2['PostalCode']]
x = []
y = []
for PostalCode in PostalCodes:
    lat, lng = latlng(PostalCode)
    x.append(lat)
    y.append(lng)
    
df2['Latitude'] = x
df2['Longitude'] = y
df2.head(15)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724
12,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
13,M3C,North York,Don Mills,43.725900,-79.340923
14,M4C,East York,Woodbine Heights,43.695344,-79.318389